# Generated by Django 6.0.2 on 2026-04-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tax_jurisdiction',
            field=models.CharField(default='us', max_length=50),
        ),
    ]
