# Generated by Django 6.0.2 on 2026-04-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_tax_jurisdiction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tax_jurisdiction',
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_country',
            field=models.CharField(default='india', max_length=50),
        ),
    ]
