# Generated by Django 6.0.2 on 2026-05-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_tax_jurisdiction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
