# Generated by Django 6.0.2 on 2026-05-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcalculation',
            name='ai_explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
